project:
  type: website

resources:
    - files/Richardson_Resume.pdf

website:
  search: false
  title: ""
  navbar:
    background: "#f8fbfd"
    left:
      - href: index.qmd
        text: Victorya Richardson
      - href: research/index.qmd
        text: Research
      - href: teaching-and-mentorship/index.qmd
        text: Teaching & Mentorship
      - href: publications/index.qmd
        text: Publications
      # - random.qmd

format:
  html:
    page-layout: full
    anchor-sections: false
    backgroundcolor: "#f8fbfd"
    theme:
      - morph
      - brand
    css: styles.css
    include-after-body: _analytics.html
    toc: false



